const state={data:null,model:"last_click",metric:"conversions"};
const $=s=>document.querySelector(s);
const fmt=new Intl.NumberFormat("pt-BR",{maximumFractionDigits:2});
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});
const modelLabels={first_click:"First-Click",last_click:"Last-Click",linear:"Linear",time_decay:"Time-Decay",position_based:"Position-Based"};
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function metricKey(){return `${state.model}_${state.metric}`}
function metricFormat(v){return state.metric==="revenue"?money.format(v):fmt.format(v)}
function pct(v){return `${fmt.format(v)}%`}
function hydrateMeta(d){$("#period").textContent=`${d.source_start_date} — ${d.source_end_date}`;$("#window").textContent=`${d.attribution_window_days} dias`;$("#halfLife").textContent=`${d.time_decay_half_life_days} dias`}
function hydrateKpis(k){$("#totalJourneys").textContent=fmt.format(k.total_journeys);$("#canonicalRevenue").textContent=money.format(k.canonical_revenue);$("#multiTouchPct").textContent=pct(k.multi_touch_pct);$("#multiTouchCount").textContent=`${fmt.format(k.multi_touch_journeys)} jornadas`;$("#multiChannelPct").textContent=pct(k.multi_channel_pct);$("#multiChannelCount").textContent=`${fmt.format(k.multi_channel_journeys)} jornadas`;$("#avgTouchpoints").textContent=fmt.format(k.avg_touchpoints);$("#p90Duration").textContent=`${fmt.format(k.p90_journey_duration_days)} dias`}
function renderChannelBars(){const key=metricKey();const rows=[...state.data.channels].sort((a,b)=>b[key]-a[key]).slice(0,10);const max=Math.max(...rows.map(r=>r[key]),1);$("#channelBars").innerHTML=rows.map(r=>`<div class="bar-row"><span class="bar-label" title="${esc(r.channel)}">${esc(r.channel)}</span><span class="bar-track"><span class="bar-fill" style="width:${(r[key]/max)*100}%"></span></span><span class="bar-value">${metricFormat(r[key])}</span></div>`).join("")}
function renderTouchpoints(){const rows=state.data.touchpoint_distribution;const max=Math.max(...rows.map(r=>r.journeys),1);$("#touchpointBars").innerHTML=rows.map(r=>`<div class="bar-row"><span class="bar-label">${r.total_touchpoints}×</span><span class="bar-track"><span class="bar-fill" style="width:${(r.journeys/max)*100}%"></span></span><span class="bar-value">${fmt.format(r.journeys)}</span></div>`).join("")}
function renderDevices(){const colors=["#176b46","#80aa94","#d3e1da","#b8c8bf"];let cursor=0;const stops=state.data.devices.map((d,i)=>{const start=cursor;cursor+=d.journey_share_pct;return `${colors[i%colors.length]} ${start}% ${cursor}%`});$("#deviceDonut").style.background=`conic-gradient(${stops.join(",")})`;$("#deviceLegend").innerHTML=state.data.devices.map((d,i)=>`<div class="legend-row"><span class="legend-dot" style="background:${colors[i%colors.length]}"></span><span>${esc(d.device_category)}</span><span>${pct(d.journey_share_pct)}</span></div>`).join("")}
function renderMonths(){const rows=state.data.monthly_trend;const max=Math.max(...rows.map(r=>r.revenue),1);$("#monthlyChart").innerHTML=rows.map(r=>`<article class="month-card"><span class="month">${esc(r.month)}</span><strong>${fmt.format(r.journeys)}</strong><small>jornadas · ${money.format(r.revenue)}</small><div class="mini-line"><span style="width:${(r.revenue/max)*100}%"></span></div><small>${fmt.format(r.avg_touchpoints)} touchpoints · ${fmt.format(r.avg_journey_duration_days)} dias</small></article>`).join("")}
function deltaClass(v){return v>0?"delta-pos":v<0?"delta-neg":""}
function renderTable(filter=""){const q=filter.trim().toLowerCase();const rows=state.data.channels.filter(r=>r.channel.toLowerCase().includes(q)).sort((a,b)=>b.last_click_conversions-a.last_click_conversions);$("#channelTable").innerHTML=rows.map(r=>`<tr><td>${esc(r.channel)}</td><td>${fmt.format(r.first_click_conversions)}</td><td>${fmt.format(r.last_click_conversions)}</td><td>${fmt.format(r.linear_conversions)}</td><td>${fmt.format(r.time_decay_conversions)}</td><td>${fmt.format(r.position_based_conversions)}</td><td class="${deltaClass(r.first_click_vs_last_click_pct)}">${r.first_click_vs_last_click_pct>0?"+":""}${pct(r.first_click_vs_last_click_pct)}</td></tr>`).join("")}
function bind(){ $("#modelSelect").addEventListener("change",e=>{state.model=e.target.value;renderChannelBars()});$("#metricSelect").addEventListener("change",e=>{state.metric=e.target.value;renderChannelBars()});$("#channelSearch").addEventListener("input",e=>renderTable(e.target.value))}
async function init(){try{const res=await fetch("./data/dashboard_data.json");if(!res.ok)throw new Error("HTTP "+res.status);state.data=await res.json();hydrateMeta(state.data);hydrateKpis(state.data.kpis);renderChannelBars();renderTouchpoints();renderDevices();renderMonths();renderTable();bind()}catch(err){console.error(err);$("#errorState").hidden=false}}
init();