const state={data:null,model:"last_click",metric:"conversions",slide:0};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const fmt=new Intl.NumberFormat("pt-BR",{maximumFractionDigits:2});
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const modelCopy={last_click:["Último contato recebe 100% do crédito.","O Last-Click privilegia canais de fechamento.","É útil operacionalmente, mas subestima quem iniciou ou assistiu a jornada."],first_click:["Primeiro contato recebe 100% do crédito.","O First-Click revela quem criou a demanda.","Google / CPC cresce 62% em relação ao Last-Click."],linear:["Todos os contatos dividem o crédito igualmente.","O Linear reduz extremos entre descoberta e fechamento.","É simples e transparente, mas trata contatos distantes como equivalentes."],time_decay:["Contatos recentes recebem mais crédito.","O Time-Decay valoriza proximidade da conversão.","A meia-vida de 7 dias favorece canais presentes no fim da jornada."],position_based:["40% ao primeiro, 40% ao último e 20% ao meio.","O Position-Based equilibra descoberta e fechamento.","Preserva as pontas da jornada sem ignorar os contatos intermediários."]};
function pct(v){return fmt.format(v)+"%"}function metricKey(){return state.model+"_"+state.metric}function metricFormat(v){return state.metric==="revenue"?money.format(v):fmt.format(v)}
function hydrateMeta(d){$("#period").textContent=d.source_start_date+" — "+d.source_end_date;$("#window").textContent=d.attribution_window_days+" dias"}
function hydrateKpis(k){$("#totalJourneys").textContent=fmt.format(k.total_journeys);$("#canonicalRevenue").textContent=money.format(k.canonical_revenue);$("#multiTouchPct").textContent=pct(k.multi_touch_pct);$("#multiTouchCount").textContent=fmt.format(k.multi_touch_journeys)+" jornadas";$("#multiChannelPct").textContent=pct(k.multi_channel_pct);$("#multiChannelCount").textContent=fmt.format(k.multi_channel_journeys)+" jornadas";$("#avgTouchpoints").textContent=fmt.format(k.avg_touchpoints)+" em média";$("#p90Duration").textContent=fmt.format(k.p90_journey_duration_days)+" dias"}
function renderChannelBars(){const key=metricKey(),rows=[...state.data.channels].sort((a,b)=>b[key]-a[key]).slice(0,9),max=Math.max(...rows.map(r=>r[key]),1);$("#channelBars").innerHTML=rows.map(r=>'<div class="bar-row"><span class="bar-label" title="'+esc(r.channel)+'">'+esc(r.channel)+'</span><span class="bar-track"><span class="bar-fill" style="width:'+(r[key]/max*100)+'%"></span></span><span class="bar-value">'+metricFormat(r[key])+'</span></div>').join("");const copy=modelCopy[state.model];$("#modelNote").textContent=copy[0];$("#channelHeadline").textContent=copy[1];$("#channelCopy").textContent=copy[2]}
function renderTouchpoints(){const rows=state.data.touchpoint_distribution,max=Math.max(...rows.map(r=>r.journeys),1);$("#touchpointBars").innerHTML=rows.map(r=>'<div class="bar-row"><span class="bar-label">'+r.total_touchpoints+'×</span><span class="bar-track"><span class="bar-fill" style="width:'+(r.journeys/max*100)+'%"></span></span><span class="bar-value">'+fmt.format(r.journeys)+'</span></div>').join("")}
function renderDevices(){const colors=["#176b46","#7da58e","#cbd7cf","#aebdb4"];let cursor=0;const stops=state.data.devices.map((d,i)=>{const start=cursor;cursor+=d.journey_share_pct;return colors[i%colors.length]+" "+start+"% "+cursor+"%"});$("#deviceDonut").style.background="conic-gradient("+stops.join(",")+")";$("#deviceLegend").innerHTML=state.data.devices.map((d,i)=>'<div class="legend-row"><span class="legend-dot" style="background:'+colors[i%colors.length]+'"></span><span>'+esc(d.device_category)+'</span><strong>'+pct(d.journey_share_pct)+'</strong></div>').join("")}
function renderMonths(){const rows=state.data.monthly_trend,max=Math.max(...rows.map(r=>r.revenue),1);$("#monthlyChart").innerHTML=rows.map(r=>'<article class="month-card"><span class="month">'+esc(r.month)+'</span><strong>'+fmt.format(r.journeys)+' jornadas</strong><small>'+money.format(r.revenue)+'</small><small>'+fmt.format(r.avg_touchpoints)+' touchpoints</small><div class="mini-line"><span style="width:'+(r.revenue/max*100)+'%"></span></div></article>').join("")}
function deltaClass(v){return v>0?"delta-pos":v<0?"delta-neg":""}function renderTable(filter=""){const q=filter.trim().toLowerCase(),rows=state.data.channels.filter(r=>r.channel.toLowerCase().includes(q)).sort((a,b)=>b.last_click_conversions-a.last_click_conversions);$("#channelTable").innerHTML=rows.map(r=>'<tr><td>'+esc(r.channel)+'</td><td>'+fmt.format(r.first_click_conversions)+'</td><td>'+fmt.format(r.last_click_conversions)+'</td><td>'+fmt.format(r.linear_conversions)+'</td><td>'+fmt.format(r.time_decay_conversions)+'</td><td>'+fmt.format(r.position_based_conversions)+'</td><td class="'+deltaClass(r.first_click_vs_last_click_pct)+'">'+(r.first_click_vs_last_click_pct>0?"+":"")+pct(r.first_click_vs_last_click_pct)+'</td></tr>').join("")}
function goToSlide(index){const slides=$$(".slide");index=Math.max(0,Math.min(index,slides.length-1));slides.forEach((s,i)=>{s.classList.toggle("active",i===index);s.classList.toggle("exit-left",i<index)});$$(".nav-dot").forEach((b,i)=>b.classList.toggle("active",i===index));state.slide=index;$("#currentSlide").textContent=String(index+1).padStart(2,"0");$("#progressBar").style.width=((index+1)/slides.length*100)+"%";history.replaceState(null,"","#slide-"+(index+1))}
function bind(){$("#modelSelect").addEventListener("change",e=>{state.model=e.target.value;renderChannelBars()});$("#metricSelect").addEventListener("change",e=>{state.metric=e.target.value;renderChannelBars()});$("#channelSearch").addEventListener("input",e=>renderTable(e.target.value));$("#prevSlide").addEventListener("click",()=>goToSlide(state.slide-1));$("#nextSlide").addEventListener("click",()=>goToSlide(state.slide+1));$$(".nav-dot").forEach((b,i)=>b.addEventListener("click",()=>goToSlide(i)));document.addEventListener("keydown",e=>{if(["ArrowRight","PageDown"," "].includes(e.key)){e.preventDefault();goToSlide(state.slide+1)}if(["ArrowLeft","PageUp"].includes(e.key)){e.preventDefault();goToSlide(state.slide-1)}if(e.key==="Home")goToSlide(0);if(e.key==="End")goToSlide(6)});let startX=0;document.addEventListener("touchstart",e=>startX=e.touches[0].clientX,{passive:true});document.addEventListener("touchend",e=>{const d=e.changedTouches[0].clientX-startX;if(Math.abs(d)>60)goToSlide(state.slide+(d<0?1:-1))},{passive:true})}
async function init(){try{const res=await fetch("./data/dashboard_data.json");if(!res.ok)throw new Error("HTTP "+res.status);state.data=await res.json();hydrateMeta(state.data);hydrateKpis(state.data.kpis);renderChannelBars();renderTouchpoints();renderDevices();renderMonths();renderTable();bind();const match=location.hash.match(/slide-(\d+)/);goToSlide(match?Number(match[1])-1:0)}catch(err){console.error(err);$("#errorState").hidden=false}}
init();